output: "db"
pkgname: "db"
wipe: true
no-tests: true
debug: true
add-panic-variants: true	
no-context: true
add-global-variants: true

mysql:
  dbname: "calendars"
  host: "127.0.0.1"
  port: 3306
  user: "root"
  pass: "password"
  sslmode: "false"